spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5b9382548728fd083910
            client-secret: 20916a01cbe4b098acf5906fa0b8bba4592e92fb