server:
  port: 8093

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          client_one:
              provider: keycloak
              client-id: client_one
              client-secret: 93a25c1c-a887-447a-a0cb-b62c7b359310
              authorization-grant-type: client_credentials
              scope: read,write
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/test/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/test/protocol/openid-connect/token

resource-server:
  base-uri: http://localhost:8092/
